version: '3.8'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - project-upload-pdf-network
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - project-upload-pdf-network
    depends_on:
      - backend

networks:
  project-upload-pdf-network:
    name: project-upload-pdf-network